window.AIRLINES = [
  ["Aegean Airlines","AEE","AEGEAN",["LKPR"]],
  ["Aer Lingus","EIN","SHAMROCK",["LKPR"]],
  ["Air Arabia","ABY","ARABIA",["LKPR"]],
  ["airBaltic","BTI","AIR BALTIC",["LKPR"]],
  ["Air Canada","ACA","AIR CANADA",["LKPR"]],
  ["Air Cairo","MSC","AIR CAIRO",["LKPR","LKTB","LKMT"]],
  ["Air Europa","AEA","EUROPA",["LKPR"]],
  ["Air France","AFR","AIRFRANS",["LKPR"]],
  ["Air Montenegro","MNE","MOUNT EAGLE",["LKPR","LKTB","LKMT"]],
  ["Air Serbia","ASL","AIR SERBIA",["LKPR"]],
  ["Arkia Israeli Airlines","AIZ","ARKIA",["LKPR"]],
  ["Asiana Airlines","AAR","ASIANA",["LKPR"]],
  ["Austrian Airlines","AUA","AUSTRIAN",["LKPR"]],
  ["Azerbaijan Airlines","AHY","AZAL",["LKPR"]],
  ["BH Air","BGH","BALKAN HOLIDAYS",["LKPR","LKTB","LKMT","LKKV"]],
  ["British Airways","BAW","SPEEDBIRD",["LKPR"]],
  ["Brussels Airlines","BEL","BEELINE",["LKPR"]],
  ["Bulgaria Air","LZB","FLYING BULGARIA",["LKPR","LKTB","LKMT"]],
  ["China Airlines","CAL","DYNASTY",["LKPR"]],
  ["Condor","CFG","CONDOR",["LKPR"]],
  ["Corendon Airlines","CAI","CORENDON",["LKPR","LKTB","LKMT"]],
  ["Croatia Airlines","CTN","CROATIA",["LKPR"]],
  ["Cyprus Airways","CYP","CYPRUS",["LKPR"]],
  ["Delta Air Lines","DAL","DELTA",["LKPR"]],
  ["easyJet","EZY","EASY",["LKPR"]],
  ["EgyptAir","MSR","EGYPTAIR",["LKPR"]],
  ["EL AL","ELY","EL AL",["LKPR"]],
  ["Emirates","UAE","EMIRATES",["LKPR"]],
  ["Enter Air","ENT","ENTERAIR",["LKPR","LKTB","LKMT"]],
  ["Etihad Airways","ETD","ETIHAD",["LKPR"]],
  ["European Air Charter","EAF","EUROCHARTER",["LKPR","LKTB","LKMT"]],
  ["Eurowings","EWG","EUROWINGS",["LKPR"]],
  ["Finnair","FIN","FINNAIR",["LKPR"]],
  ["flydubai","FDB","SKY DUBAI",["LKPR"]],
  ["FLYONE","FIA","FLY ONE",["LKPR"]],
  ["Freebird Airlines","FHY","FREEBIRD",["LKPR","LKTB","LKMT"]],
  ["Georgian Airways","TGZ","TAMAZI",["LKPR"]],
  ["Hainan Airlines","CHH","HAINAN",["LKPR"]],
  ["Iberia","IBE","IBERIA",["LKPR"]],
  ["Icelandair","ICE","ICEAIR",["LKPR"]],
  ["Israir Airlines","ISR","ISRAIR",["LKPR"]],
  ["Jet2.com","EXS","CHANNEX",["LKPR"]],
  ["KLM Royal Dutch Airlines","KLM","KLM",["LKPR"]],
  ["Korean Air","KAL","KOREANAIR",["LKPR"]],
  ["LOT Polish Airlines","LOT","LOT",["LKPR","LKMT"]],
  ["Lufthansa","DLH","LUFTHANSA",["LKPR"]],
  ["Luxair","LGL","LUXAIR",["LKPR"]],
  ["KM Malta Airlines","KMM","SKY KNIGHT",["LKPR"]],
  ["Neos","NOS","MOONFLOWER",["LKPR"]],
  ["Norwegian Air Shuttle","NOZ","NORSEMAN",["LKPR"]],
  ["Nouvelair","LBT","NOUVELAIR",["LKPR"]],
  ["Pegasus Airlines","PGT","SUNTURK",["LKPR"]],
  ["PLAY","FPY","PLAYER",["LKPR"]],
  ["Qanot Sharq","QNT","QANOT SHARQ",["LKPR"]],
  ["Qatar Airways","QTR","QATARI",["LKPR"]],
  ["Ryanair","RYR","RYANAIR",["LKPR","LKTB","LKMT"]],
  ["SAS Scandinavian Airlines","SAS","SCANDINAVIAN",["LKPR"]],
  ["Saudia","SVA","SAUDIA",["LKPR"]],
  ["Sky Express","SEH","AIR CRETE",["LKPR"]],
  ["Smartwings","TVS","SKYTRAVEL",["LKPR","LKTB","LKMT"]],
  ["SunExpress","SXS","SUNEXPRESS",["LKPR","LKTB","LKMT"]],
  ["SWISS","SWR","SWISS",["LKPR"]],
  ["TAP Air Portugal","TAP","AIR PORTUGAL",["LKPR"]],
  ["TAROM","ROT","TAROM",["LKPR"]],
  ["Tailwind Airlines","TWI","TAILWIND",["LKPR","LKTB","LKMT"]],
  ["Transavia","TRA","TRANSAVIA",["LKPR"]],
  ["Transavia France","TVF","FRANCE SOLEIL",["LKPR"]],
  ["Tunisair","TAR","TUNAIR",["LKPR","LKTB","LKMT"]],
  ["Turkish Airlines","THY","TURKISH",["LKPR"]],
  ["United Airlines","UAL","UNITED",["LKPR"]],
  ["Uzbekistan Airways","UZB","UZBEKISTAN",["LKPR"]],
  ["Volotea","VOE","VOLOTEA",["LKPR"]],
  ["Vueling","VLG","VUELING",["LKPR"]],
  ["Wizz Air","WZZ","WIZZ AIR",["LKPR"]],
  ["World2Fly","WFL","BLUE WORLD",["LKPR"]]
].map(([airline,icao,callsign,airports]) => ({airline,icao,callsign,airports}));
